apiVersion: v1
kind: Service
metadata:
  name: {{ include "psql-script-generator-api.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "psql-script-generator-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPortName }}
      protocol: TCP
      name: http
  selector:
    {{- include "psql-script-generator-api.selectorLabels" . | nindent 4 }}
